name: brick_breaker
description: Brick Breaker is a fun and addictive game where you break bricks using a bouncing ball.
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.1
  get_it: ^7.6.0
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/images/ball.png